# datasource
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadinho?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jackson:
    default-property-inclusion: non_null
